apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  type: NodePort
  ports:
    - name: http
      port: 8081
      nodePort: 31001

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - env:
            - name: DB_SERVER
              value: database
            - name: MYSQL_DATABASE
              value: videodb
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: "1111"
          image: kil1menaz/user-service
          name: user-service
          ports:
            - name: http
              containerPort: 8081

---